#!/usr/bin/env python

Import("env")


env.add_source_files(env.modules_sources, "*.cpp")
env.Append(LIBS=["libbreakpad_client"])

env.Append(RPATH=["."])
env.Append(LIBPATH=["#thirdparty/breakpad"])
#env.Append(LINKFLAGS=["#thirdparty/breakpad/libbreakpad_client.a"])
env.Append(CPPPATH=["#thirdparty/breakpad/src"])
