#!/usr/bin/env python

Import("env")


env.add_source_files(env.modules_sources, "*.cpp")

if env["platform"] == "x11":
    env.Append(LIBS=["libbreakpad_client"])
    
    env.Append(RPATH=["."])
    env.Append(LIBPATH=["#thirdparty/breakpad"])
    env.Append(CPPPATH=["#thirdparty/breakpad/src"])
